name: Deploy to Google cloud run

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2

      -
        name: create .env file
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          printenv > .env

      -
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      -
        name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      -
        name: Use gcloud CLI
        run: gcloud info

      -
        name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
        
      -
        name: Build Image
        run: |
          docker build -f Dockerfile.dev -t smartglass:${{ github.sha }} . --network=host

      -
        name: Tag Image
        run: |
          docker tag smartglass:${{ github.sha }} us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mxaxaxbx/smartglass:${{ github.sha }}
      
      -
        name: Push Image
        run: |
          docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mxaxaxbx/smartglass:${{ github.sha }}

      -
        name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy smartglass \
            --concurrency 80 \
            --min-instances 0 \
            --max-instances 1 \
            --timeout 300s \
            --cpu 1 \
            --memory 512Mi \
            --image us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mxaxaxbx/smartglass:${{ github.sha }} \
            --region us-east1 \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SA_EMAIL }}

      -
        name: Remove Image from artifact registry
        run: |
          gcloud container images delete \
            us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mxaxaxbx/smartglass:${{ github.sha }} \
            --force-delete-tags \
            --quiet
